# Generated by Django 3.0.1 on 2019-12-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('name', models.CharField(max_length=60)),
                ('dob', models.DateField()),
                ('location', models.TextField(max_length=60)),
                ('pic_url', models.TextField(max_length=140)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
