# Generated by Django 3.0.1 on 2019-12-26 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='api.User')),
                ('profile_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='api.User')),
            ],
        ),
    ]
